Using the same nyc-ticket-violation dataset, letâ€™s assume that tickets can be dismissed 
if the license plate, state, and/or street name are all there but without requiring the make of car. 
Remove rows that are missing one or more of these. How many rows remain? Assuming $100/ticket,
how much money would the city lose as a result of this?

In [1]:
import pandas as pd

# Load the CSV file into a DataFrame
df = pd.read_csv('violations.csv')
df

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,4714702166,KGK6659,NY,PAS,11/12/2020,36,4DSD,BMW,V,0,...,GY,NaN,2007,NaN,0,NaN,PHTO SCHOOL ZN SPEED VIOLATION,NaN,NaN,NaN
1,8793684599,L5232HY,TN,PAS,09/14/2020,21,TRAC,INTER,T,60790,...,WHITE,NaN,0,NaN,0,W,NaN,NaN,NaN,NaN
2,8864757053,BPMN76,FL,PAS,11/25/2020,20,SUBN,NISSA,T,36030,...,BLACK,NaN,0,NaN,0,49,20A-No Parking (Non-COM),NaN,NaN,NaN
3,8778326047,57387MJ,NY,COM,08/20/2020,38,VAN,NaN,T,34430,...,WH,NaN,2016,NaN,0,01,NaN,NaN,NaN,NaN
4,4706640702,M81KFJ,NJ,PAS,09/09/2020,36,UT,TOYOT,V,0,...,NaN,NaN,2002,NaN,0,NaN,PHTO SCHOOL ZN SPEED VIOLATION,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,4014245755,JPN4910,NY,PAS,06/25/2020,5,PICK,FORD,V,0,...,RD,NaN,2019,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
49996,8794437506,174ZYG,CT,PAS,08/25/2020,31,4DSD,TOYOT,T,34030,...,BLACK,NaN,0,NaN,0,16,NaN,NaN,NaN,NaN
49997,8849769581,HES6895,NY,PAS,11/03/2020,46,SUBN,CADIL,T,27120,...,RD,NaN,2005,NaN,0,K,NaN,NaN,NaN,NaN
49998,8755448173,63035MN,NY,COM,08/19/2020,40,DELV,ISUZU,T,0,...,WH,NaN,2020,NaN,5,67,NaN,NaN,NaN,NaN
49999,8581527528,AW74165,CT,PAS,08/06/2020,20,4DSD,HONDA,T,17860,...,BLACK,NaN,0,NaN,0,A,NaN,NaN,NaN,NaN

In [4]:
# Filter out rows with missing required fields
no_na_set_df = df.dropna(subset=['Plate ID', 'Registration State', 'Street Name'])
no_na_set_df

,Summons Number,Plate ID,Registration State,Plate Type,Issue Date,Violation Code,Vehicle Body Type,Vehicle Make,Issuing Agency,Street Code1,...,Vehicle Color,Unregistered Vehicle?,Vehicle Year,Meter Number,Feet From Curb,Violation Post Code,Violation Description,No Standing or Stopping Violation,Hydrant Violation,Double Parking Violation
0,4714702166,KGK6659,NY,PAS,11/12/2020,36,4DSD,BMW,V,0,...,GY,NaN,2007,NaN,0,NaN,PHTO SCHOOL ZN SPEED VIOLATION,NaN,NaN,NaN
1,8793684599,L5232HY,TN,PAS,09/14/2020,21,TRAC,INTER,T,60790,...,WHITE,NaN,0,NaN,0,W,NaN,NaN,NaN,NaN
2,8864757053,BPMN76,FL,PAS,11/25/2020,20,SUBN,NISSA,T,36030,...,BLACK,NaN,0,NaN,0,49,20A-No Parking (Non-COM),NaN,NaN,NaN
3,8778326047,57387MJ,NY,COM,08/20/2020,38,VAN,NaN,T,34430,...,WH,NaN,2016,NaN,0,01,NaN,NaN,NaN,NaN
4,4706640702,M81KFJ,NJ,PAS,09/09/2020,36,UT,TOYOT,V,0,...,NaN,NaN,2002,NaN,0,NaN,PHTO SCHOOL ZN SPEED VIOLATION,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,4014245755,JPN4910,NY,PAS,06/25/2020,5,PICK,FORD,V,0,...,RD,NaN,2019,NaN,0,NaN,BUS LANE VIOLATION,NaN,NaN,NaN
49996,8794437506,174ZYG,CT,PAS,08/25/2020,31,4DSD,TOYOT,T,34030,...,BLACK,NaN,0,NaN,0,16,NaN,NaN,NaN,NaN
49997,8849769581,HES6895,NY,PAS,11/03/2020,46,SUBN,CADIL,T,27120,...,RD,NaN,2005,NaN,0,K,NaN,NaN,NaN,NaN
49998,8755448173,63035MN,NY,COM,08/19/2020,40,DELV,ISUZU,T,0,...,WH,NaN,2020,NaN,5,67,NaN,NaN,NaN,NaN
49999,8581527528,AW74165,CT,PAS,08/06/2020,20,4DSD,HONDA,T,17860,...,BLACK,NaN,0,NaN,0,A,NaN,NaN,NaN,NaN

In [5]:
no_na_set_df.isnull().sum()

Summons Number                           0
Plate ID                                 0
Registration State                       0
Plate Type                               0
Issue Date                               0
Violation Code                           0
Vehicle Body Type                      143
Vehicle Make                           134
Issuing Agency                           0
Street Code1                             0
Street Code2                             0
Street Code3                             0
Vehicle Expiration Date                  0
Violation Location                   17890
Violation Precinct                       0
Issuer Precinct                          0
Issuer Code                              0
Issuer Command                       17857
Issuer Squad                         17857
Violation Time                           1
Time First Observed                  48101
Violation County                       111
Violation In Front Of Or Opposite    18063
House Number                         18264
Street Name                              0
Intersecting Street                  27276
Date First Observed                      0
Law Section                              0
Sub Division                             0
Violation Legal Code                 32133
Days Parking In Effect               17857
From Hours In Effect                 30392
To Hours In Effect                   30392
Vehicle Color                         2415
Unregistered Vehicle?                47888
Vehicle Year                             0
Meter Number                         47843
Feet From Curb                           0
Violation Post Code                  19959
Violation Description                27191
No Standing or Stopping Violation    49990
Hydrant Violation                    49990
Double Parking Violation             49990
dtype: int64

In [6]:
no_na_set_df= df.dropna()
no_na_set_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 43 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Summons Number                     0 non-null      int64
 1   Plate ID                           0 non-null      object
 2   Registration State                 0 non-null      object
 3   Plate Type                         0 non-null      object
 4   Issue Date                         0 non-null      object
 5   Violation Code                     0 non-null      int64
 6   Vehicle Body Type                  0 non-null      object
 7   Vehicle Make                       0 non-null      object
 8   Issuing Agency                     0 non-null      object
 9   Street Code1                       0 non-null      int64
 10  Street Code2                       0 non-null      int64
 11  Street Code3                       0 non-null      int64
 12  Vehicle Expiration Date            0 non-null      int64
 13  Violation Location                 0 non-null      float64
 14  Violation Precinct                 0 non-null      int64
 15  Issuer Precinct                    0 non-null      int64
 16  Issuer Code                        0 non-null      int64
 17  Issuer Command                     0 non-null      object
 18  Issuer Squad                       0 non-null      object
 19  Violation Time                     0 non-null      object
 20  Time First Observed                0 non-null      object
 21  Violation County                   0 non-null      object
 22  Violation In Front Of Or Opposite  0 non-null      object
 23  House Number                       0 non-null      object
 24  Street Name                        0 non-null      object
 25  Intersecting Street                0 non-null      object
 26  Date First Observed                0 non-null      int64
 27  Law Section                        0 non-null      int64
 28  Sub Division                       0 non-null      object
 29  Violation Legal Code               0 non-null      object
 30  Days Parking In Effect             0 non-null      object
 31  From Hours In Effect               0 non-null      object
 32  To Hours In Effect                 0 non-null      object
 33  Vehicle Color                      0 non-null      object
 34  Unregistered Vehicle?              0 non-null      float64
 35  Vehicle Year                       0 non-null      int64
 36  Meter Number                       0 non-null      object
 37  Feet From Curb                     0 non-null      int64
 38  Violation Post Code                0 non-null      object
 39  Violation Description              0 non-null      object
 40  No Standing or Stopping Violation  0 non-null      float64
 41  Hydrant Violation                  0 non-null      float64
 42  Double Parking Violation           0 non-null      float64
dtypes: float64(5), int64(13), object(25)
memory usage: 0.0+ bytes

In [7]:
print(".......................remaining rows.................................")

.......................remaining rows.................................

In [8]:
# Count the number of remaining rows
num_rows = len(df.index)
print(f' The number of  rows remaining {num_rows}')

 The number of  rows remaining 49990

In [9]:
print(".......................Amount remaining.................................")

.......................Amount remaining.................................

In [10]:
# Calculate the amount of money the city would lose
money_lost = num_rows * 100
print( f'The total amount of money remain is $ {money_lost}' )

The total amount of money remain is $ 4999000